In [36]:
import pandas as pd
import numpy as np

# Creare un DataFrame di esempio
data = {
    'Colonna1': [1, 2, 3, 4],
    'Colonna2': [5.1, 6.2, 7.3, 8.4],
    'Colonna3': ['2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01'],
    'Colonna4': ['A', 'B', 'A', 'C'],
    'Colonna5': [True, False, True, False]
}

df = pd.DataFrame(data)
df

   Colonna1  Colonna2    Colonna3 Colonna4  Colonna5
0         1       5.1  2022-01-01        A      True
1         2       6.2  2022-02-01        B     False
2         3       7.3  2022-03-01        A      True
3         4       8.4  2022-04-01        C     False

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Colonna1  4 non-null      int64
 1   Colonna2  4 non-null      float64
 2   Colonna3  4 non-null      object
 3   Colonna4  4 non-null      object
 4   Colonna5  4 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(2)
memory usage: 264.0+ bytes

In [38]:
from numpy import float64
# 1. Convertire la Colonna1 da int a float

df["Colonna1"] = df["Colonna1"].astype(float64)
df["Colonna1"]

0    1.0
1    2.0
2    3.0
3    4.0
Name: Colonna1, dtype: float64

In [39]:
# 2. Convertire la Colonna2 da float a int
df["Colonna2"] = df["Colonna2"].astype(int)
df["Colonna2"]

0    5
1    6
2    7
3    8
Name: Colonna2, dtype: int64

In [40]:
#datetime
# 3. Convertire la Colonna3 da stringa a data
df["Colonna3"] = pd.to_datetime(df["Colonna3"])
df["Colonna3"]

0   2022-01-01
1   2022-02-01
2   2022-03-01
3   2022-04-01
Name: Colonna3, dtype: datetime64[ns]

In [41]:
# 4. Convertire la Colonna3 da data a stringa
df["Colonna3"] = df["Colonna3"].astype("string")
df["Colonna3"]

0    2022-01-01
1    2022-02-01
2    2022-03-01
3    2022-04-01
Name: Colonna3, dtype: string

In [42]:
#category
# 5. Convertire la Colonna4 da object a categoria
df["Colonna4"] = df["Colonna4"].astype("category")
df["Colonna4"]

0    A
1    B
2    A
3    C
Name: Colonna4, dtype: category
Categories (3, object): ['A', 'B', 'C']

In [43]:
# 6. Convertire la Colonna4 da categoria a object
df["Colonna4"] = df["Colonna4"].astype("string")
df["Colonna4"]

0    A
1    B
2    A
3    C
Name: Colonna4, dtype: string

In [44]:
# 7. Convertire più colonne contemporaneamente
#'Colonna1'float 'Colonna2'int 'Colonna4''category'
df.astype({"Colonna1" : float, "Colonna2":int,"Colonna4" : "category"})

   Colonna1  Colonna2    Colonna3 Colonna4  Colonna5
0       1.0         5  2022-01-01        A      True
1       2.0         6  2022-02-01        B     False
2       3.0         7  2022-03-01        A      True
3       4.0         8  2022-04-01        C     False

In [46]:
# 8. Convertire tutti i tipi di dati del DataFrame in float
"""df.astype(float)"""

ValueError: could not convert string to float: 'A'

In [48]:
# 9. Convertire la Colonna5 da booleana a intero
df['Colonna5']=df['Colonna5'].astype(int)
df["Colonna5"]

0    1
1    0
2    1
3    0
Name: Colonna5, dtype: int64

In [49]:
# 10. Convertire la Colonna5 da intero a booleano
df["Colonna5"]=df["Colonna5"].astype(bool)
df["Colonna5"]

0     True
1    False
2     True
3    False
Name: Colonna5, dtype: bool